#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
use File::Basename;
use File::Path;

foreach my $file (qw(/etc/yum.conf /etc/sysconfig/protected-packages
                     /etc/yum.smerepos.d/sme-base.repo))
{
    templates2events($file, qw(
        yum-modify
        bootstrap-console-save
        nethupdate-install-systemid
        post-upgrade
    ));
}

templates2events("/etc/crontab", "yum-modify");

for ( qw(install remove update) )
{
    event_link("yum-action", "yum-$_", "20");
    event_link("initialize-default-databases", "yum-$_", "50");
    event_link("navigation-conf", "yum-$_", "80");
}

for ( qw(install remove update modify) )
{
    event_link("yum-update-dbs", "yum-$_", "90");
}

for ( qw(bootstrap-console-save yum-update) )
{
    event_link("yum-import-keys", $_, "10");
}

safe_symlink("once", "root/etc/e-smith/events/local/services2adjust/yum");

#--------------------------------------------------
# functions for manager panel
#--------------------------------------------------
panel_link("nethupdate", "manager");

#--------------------------------------------------
# nethupdate
#--------------------------------------------------
safe_touch("root/etc/e-smith/db/configuration/defaults/nethupdate/SystemID");
event_link("yum-update-system", "nethupdate-install-systemid", "70");
service_link_enhanced("yum-cron", "S90", "7");

