#!/usr/bin/perl -wT
# vim: ft=xml:

#----------------------------------------------------------------------
# heading     : Configuration
# description : Software installer
# navigation  : 4000 4200
#
# copyright (C) 2005 Nethesis
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------

use strict;
use esmith::TestUtils;
use esmith::FormMagick::Panel::nethupdate;
my $f = esmith::FormMagick::Panel::nethupdate->new();

if (-e "/var/run/yum.pid")
{
    $f->print_yum_status_page();
    exit(0);
}

if ($f->get_prop('yum', 'LogFile'))
{   
    $f->skip_to_postupgrade();
}

$f->display();

__DATA__
<form
    title="FORM_TITLE"
    header="/etc/e-smith/web/common/head.tmpl"
    footer="/etc/e-smith/web/common/foot.tmpl">

    <page name="First"  pre-event="print_status_message()">
        <field
            type="literal"
            value="">
            <description>DESC_SYSTEMID_EXPLANATION</description>
        </field>
        <field
            type="literal"
            id="NethupdateSystemID"
            display="is_nethupdate_systemid_present()"
            value="get_nethupdate_systemid()">
            <label>LABEL_NETHUPDATE_SYSTEMID</label>
        </field>
        <field
            type="literal"
            id="NethupdateInsertSystemID"
            display="is_nethupdate_systemid_not_present()"
            value="">
            <description>DESC_BUTTON_INSERT_SYSTEMID</description>
        </field>
        <field
            type="literal"
            id="Nethupdate"
            display="is_nethupdate_systemid_present()"
            value="">
            <description>DESC_INSTALL_NETHEXTRA_PACKAGES</description>
        </field>
        <field
            type="literal"
            id="NethInstallSoftware"
            display="is_nethupdate_systemid_present()"
            value="">
            <description>DESC_BUTTON_INSTALL_NETHEXTRA_PACKAGES</description>
        </field>
    </page>

    <page name="NETHUPDATE_INSERT_SYSTEMID" pre-event="print_status_message()" post-event="register_nethupdate_systemid()">
        <field
            type="text"
            id="NethSystemID"
            value="get_nethupdate_systemid()"
            validation="validate_nethupdate_systemid()"
            size="60">
            <label>LABEL_NETHUPDATE_SYSTEMID</label>
            <description>DESC_SYSTEMID_EXPLANATION</description>
        </field>
        <subroutine src="print_button('NETHUPDATE_INSERT_SYSTEMID')"/>
    </page>

    <page name="NETHEXTRA_INSTALL_PACKAGES" pre-event="initialize_nethextra()" post-event="do_yum('install')">
        <subroutine src="print_status_message()"/>
        <subroutine src="print_installed_nethextra()"/>
        <field
            type="select" multiple="1"
            id="SelectedPackages"
            display="is_nethextra_available()"
            options="get_nethextra_packages('available')">
            <label>LABEL_NETHEXTRA_PACKAGES</label>
            <description>DESC_NETHEXTRA_PACKAGES</description>
        </field>
        <field
            type="literal"
            id="NoPackagesToInstall"
            display="is_nethextra_not_available()">
            <description>NETHEXTRA_NO_AVAILABLE_PACKAGES</description>
        </field>
        <subroutine src="print_skip_header()"/>
        <subroutine src="print_install_nethextra_button()"/>
    </page>

    <page name="YUM_PAGE_POSTUPGRADE" 
        pre-event="print_status_message()">

        <subroutine src="display_yum_log()" />
    </page>

</form>
