#!/usr/bin/perl -w
#----------------------------------------------------------------------
# Yum actions
# Copyright (C) 2005-2006 Gordon Rowell <gordonr@gormand.com.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License or more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

use strict;
use warnings;
use esmith::ConfigDB;

use constant YUM_CMD => qw(/usr/bin/yum -d 2 -e 2 -y);

my $db = esmith::ConfigDB->open or die "Couldn't open ConfigDB\n";

my $event = $ARGV[0];

my $function = $event;
$function =~ s/yum-//;

die "Unknown function $function\n" 
    unless ($function =~ /install|update|remove/);

my $type = $ARGV[1]; # can be "group" or "package"

my @list;

foreach my $argnum (2 .. $#ARGV) {
  push(@list, $ARGV[$argnum]);
}
my $log_file = "/var/log/yum.ouput";

open STDOUT, '>', "$log_file" or die "Can't redirect STDOUT: $!";
open STDERR, ">&STDOUT"     or die "Can't dup STDOUT: $!";

# Make yum send output immediately, so server-manager sees progress
$ENV{PYTHONUNBUFFERED} = 1;


if ($type eq "group")
{
    system(YUM_CMD, "group$function", @list) == 0 or
	die "yum group$function @list failed: $?\n";
}
elsif ($type eq "package")
{
    system(YUM_CMD, $function, @list) == 0 or
	die "yum $function @list failed: $?\n";
}

exit 0;
